Mc 1.17 refactor reorganize
OpenCubicChunks/CubicChunks2 pull request #26
Opened 2021-09-16 03:19 UTC by Barteks2x

Resubmitting from https://github.com/OpenCubicChunks/CubicChunks/pull/737

Review commit by commit.

2021-09-16 03:24 UTC, Barteks2x commented
This is ready for review

2021-09-16 03:48 UTC, NotStirred commented
Perhaps add a`.git-blame-ignore-revs` specifying these commits

2021-09-16 22:18 UTC, NotStirred commented
rename `MixinChunkMap#on_func_219244_a_StatusChange`

2021-09-16 23:48 UTC, NotStirred requested changes
Some minor things to be changed:

`ImposterProtoCube` commented out code at line @ 243

all remaining srg `field_xxxxxx_x` names
```
MixinChunkMap.java:155
MixinChunkMap.java:157
```

all remaining srg `p_` names

```
PlayerTicketTrackerFactoryAccess.java:11
FixedPlayerDistanceChunkTrackerFactoryAccess.java:11
MixinClientLevel.java:48
MixinClientLevel.java:49
MixinChunkHolder.java:103
MixinChunkMap.java:347
MixinChunkMap.java:348
MixinChunkMap.java:540
MixinChunkMap.java:849
MixinChunkMap.java:850
MixinChunkMap.java:874
MixinDistanceManager.java:71
MixinLayerLightSectionStorage.java:47
CubeMap.java:59
CubeMap.java:60
RegionCubeIO.java:124
RegionCubeIO.java:315
RegionCubeIO.java:316
CubePos.java:98
CubePos.java:99
CubePos.java:100
CubePos.java:101
ImposterProtoCube.java:193
ImposterProtoCube.java:194
ImposterProtoCube.java:197
ImposterProtoCube.java:236
ImposterProtoCube.java:244
ImposterProtoCube.java:245
ImposterProtoCube.java:250
ImposterProtoCube.java:251
```

all remaining srg `func_` names
```
MixinChunkMap.java:513
MixinChunkMap.java:518
MixinChunkMap.java:519
MixinChunkMap.java:1209
MixinChunkMap.java:1250
CubeMap.java:71
CubicPlayerTicketTracker.java:112
```

2021-09-16 23:48 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/client/multiplayer/ClientCubeCacheStorage.java
> +        LevelCube oldCUbe = this.cubes.getAndSet(cubeIndex, replaceWith);
typo

2021-09-16 23:48 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/blockentity/MixinConduitBlockEntity.java
> +    private static AABB on$expand(AABB aabb, double x, double y, double z, Level level, BlockPos pos, List<BlockPos> activatingBlocks) {
rename to match `MixinBeaconBlockEntity#limitBeaconEffectYRange`

2021-09-16 23:48 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/mixin/core/common/chunk/MixinLevelChunk.java
>  //        if (isColumn) {
Remove 1.12 logic, replaced by isCubic check

2021-09-16 23:48 UTC, NotStirred commented on src/main/java/io/github/opencubicchunks/cubicchunks/server/level/CubeMap.java
>      // replacement of func_219215_b, checkerboardDistance, checks iew distance instead of returning distance
remove srg names

2021-09-17 00:57 UTC, NotStirred approved these changes

2021-09-17 01:06 UTC, merged